# Generated by Django 4.1.7 on 2023-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.CharField(max_length=50, unique=True)),
                ("owner", models.CharField(max_length=50)),
                ("target", models.BigIntegerField()),
                ("reward", models.BigIntegerField()),
                ("duration", models.BigIntegerField()),
                ("source", models.BigIntegerField()),
                ("claimable", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
