# Generated by Django 4.1.7 on 2023-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="deadline",
            field=models.BigIntegerField(default=604800),
        ),
        migrations.AddField(
            model_name="quest",
            name="quester",
            field=models.CharField(default="0x0", max_length=50),
        ),
    ]
