# Generated by Django 4.1.7 on 2023-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_quest_deadline_quest_quester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="deadline",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="quest",
            name="quester",
            field=models.CharField(max_length=50),
        ),
    ]
