# Generated by Django 4.1.7 on 2023-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_quest_deadline_alter_quest_quester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="deadline",
            field=models.BigIntegerField(null=True),
        ),
    ]
