# Generated by Django 4.1.7 on 2023-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_quest_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="source",
        ),
        migrations.AddField(
            model_name="quest",
            name="questIndex",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quest",
            name="value",
            field=models.BigIntegerField(null=True),
        ),
    ]
