# Generated by Django 4.1.7 on 2023-06-05 06:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_quest_args"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="args",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, default=list, size=None
            ),
        ),
    ]
